package com.jiahan.smartcamera.database.dao

import android.content.Context
import androidx.room.Room
import androidx.test.core.app.ApplicationProvider
import androidx.test.ext.junit.runners.AndroidJUnit4
import com.jiahan.smartcamera.database.AppDatabase
import com.jiahan.smartcamera.database.data.DatabasePhoto
import kotlinx.coroutines.flow.first
import kotlinx.coroutines.runBlocking
import org.junit.After
import org.junit.Assert.assertEquals
import org.junit.Assert.assertNull
import org.junit.Assert.assertTrue
import org.junit.Before
import org.junit.Test
import org.junit.runner.RunWith

/**
 * Instrumented tests for [PhotoDao] against an in-memory Room database.
 */
@RunWith(AndroidJUnit4::class)
class PhotoDaoTest {

    private lateinit var database: AppDatabase
    private lateinit var photoDao: PhotoDao

    @Before
    fun createDb() {
        val context = ApplicationProvider.getApplicationContext<Context>()
        database = Room.inMemoryDatabaseBuilder(context, AppDatabase::class.java)
            .allowMainThreadQueries()
            .build()
        photoDao = database.photoDao()
    }

    @After
    fun closeDb() {
        database.close()
    }

    private fun photo(
        title: String,
        originalName: String = "$title.jpg",
        path: String = "/storage/$title.jpg",
        saveDate: Long = 0L,
    ) = DatabasePhoto(
        title = title,
        originalName = originalName,
        path = path,
        saveDate = saveDate,
    )

    @Test
    fun insertPhotos_thenGetPhotos_returnsThemOrderedBySaveDateDescending() = runBlocking {
        photoDao.insertPhotos(
            photo("oldest", saveDate = 100L),
            photo("newest", saveDate = 300L),
            photo("middle", saveDate = 200L),
        )

        val photos = photoDao.getPhotos().first()

        assertEquals(listOf("newest", "middle", "oldest"), photos.map { it.title })
    }

    @Test
    fun getPhotoByPath_returnsPhotoMatchingOriginalName() = runBlocking {
        photoDao.insertPhotos(photo("sunset", originalName = "sunset_original.jpg"))

        val result = photoDao.getPhotoByPath("sunset_original.jpg")

        assertEquals("sunset", result?.title)
    }

    @Test
    fun getImageById_returnsInsertedPhoto() = runBlocking {
        photoDao.insertPhotos(photo("beach", originalName = "beach.jpg"))
        val inserted = photoDao.getPhotoByPath("beach.jpg") ?: return@runBlocking

        val byId = photoDao.getImageById(inserted.id)

        assertEquals("beach", byId?.title)
    }

    @Test
    fun deleteImage_removesOnlyMatchingPhoto() = runBlocking {
        photoDao.insertPhotos(photo("keep", originalName = "keep.jpg"))
        photoDao.insertPhotos(photo("remove", originalName = "remove.jpg"))
        val toRemove = photoDao.getPhotoByPath("remove.jpg") ?: return@runBlocking

        photoDao.deleteImage(toRemove.id)

        val photos = photoDao.getPhotos().first()
        assertEquals(1, photos.size)
        assertEquals("keep", photos.first().title)
    }

    @Test
    fun searchPhotos_matchesTitleSubstring() = runBlocking {
        photoDao.insertPhotos(
            photo("mountain view", originalName = "1.jpg"),
            photo("city view", originalName = "2.jpg"),
            photo("portrait", originalName = "3.jpg"),
        )

        val results = photoDao.searchPhotos("view").first()

        assertEquals(setOf("mountain view", "city view"), results.map { it.title }.toSet())
    }

    @Test
    fun deletePhotos_clearsTable() = runBlocking {
        photoDao.insertPhotos(
            photo("a", originalName = "a.jpg"),
            photo("b", originalName = "b.jpg")
        )

        photoDao.deletePhotos()

        assertTrue(photoDao.getPhotos().first().isEmpty())
    }

    @Test
    fun autoGeneratedId_startsAtOne_andResetsAfterDeleteSequence() = runBlocking {
        photoDao.insertPhotos(photo("first", originalName = "first.jpg"))
        val firstId = (photoDao.getPhotoByPath("first.jpg") ?: return@runBlocking).id
        assertEquals(1, firstId)

        photoDao.deletePhotos()
        photoDao.deleteSequence()

        photoDao.insertPhotos(photo("again", originalName = "again.jpg"))
        val resetId = (photoDao.getPhotoByPath("again.jpg") ?: return@runBlocking).id
        assertEquals(1, resetId)
    }

    @Test
    fun getImageById_returnsNullWhenMissing() = runBlocking {
        assertNull(photoDao.getImageById(999))
    }
}