name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

#  unit test
#  build debug apk and android test apk
#  upload artifact (apk)
#  instrumented test / firebase test lab
#  release to play store

jobs:
  unit_test:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run unit tests
        #
        run: ./gradlew test --stacktrace

  instrumented_test:
    runs-on: macos-latest

    strategy:
      matrix:
        api-level: [21, 23, 29]

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Run instrumented tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          #
          script: ./gradlew connectedCheck --stacktrace

  apk_upload:
    runs-on: ubuntu-latest
    needs: [unit_test, instrumented_test]

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build apk
        #
        run: ./gradlew assemble --stacktrace

      - name: Upload debug apk
        uses: actions/upload-artifact@v1
        with:
          name: app-debug apk
          path: app/build/outputs/apk/debug/app-debug.apk

      - name: Upload release apk
        uses: actions/upload-artifact@v1
        with:
          name: app-release apk
          path: app/build/outputs/apk/release/app-release-unsigned.apk

      - name: Build android test apk
        #
        run: ./gradlew assembleAndroidTest --stacktrace

      - name: Upload android test apk
        uses: actions/upload-artifact@v1
        with:
          name: app-androidtest apk
          path: app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk


